[package]
name = "chat"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
base64 = "0.22.1"
colored = "3.1.1"
dotenvy = "0.15.7"
futures-util = "0.3.32"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
sha1 = "0.11.0"
sqlx = { version = "0.9", features = ["mysql", "runtime-tokio", "macros", "chrono", "mysql-rsa"] }
tokio = { version = "1.53", features = ["full"]}
tokio-tungstenite = "0.30.0"
urlencoding = "2.1.3"
